name: Build Android APK

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    - name: Install MAUI Workload
      run: dotnet workload install maui --ignore-failed-sources
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build src/KeepAll.App/KeepAll.App.csproj -c Release -f net8.0-android
    
    - name: Publish APK
      run: dotnet publish src/KeepAll.App/KeepAll.App.csproj -c Release -f net8.0-android -p:AndroidPackageFormat=apk -o ./artifacts
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: KeepAll-Android-APK
        path: ./artifacts/*.apk
        retention-days: 30

  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Run tests
      run: dotnet test --no-restore --verbosity normal
